# Generated by Django 4.0.2 on 2022-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-03-11'),
            preserve_default=False,
        ),
    ]
